Implemented support for multiple network models

diff --git a/scripts/checks b/scripts/checks
--- a/scripts/checks
+++ b/scripts/checks
@@ -18,11 +18,11 @@
 
 # Checks whether a network expression is given. Exits with status 1 if not set.
 
-checkNetworkFile()
+checkNetworkFiles()
 {
-    if [ "$networkFile" = "" ]
+    if [ "$networkFiles" = "" ]
     then
-	echo "ERROR: A network expression must be specified!" >&2
+	echo "ERROR: At least one network expression must be specified!" >&2
 	exit 1
     fi
 }
diff --git a/scripts/disnixos-deploy-network.in b/scripts/disnixos-deploy-network.in
--- a/scripts/disnixos-deploy-network.in
+++ b/scripts/disnixos-deploy-network.in
@@ -20,7 +20,7 @@
 
 showUsage()
 {
-    echo "Usage: $0 [options] network_expr"
+    echo "Usage: $0 [options] network_expr ..."
     echo "Options:"
     echo
     echo "--target-property   The target property of an infrastructure model, that specifies how to "
@@ -82,17 +82,21 @@ checkShowTrace
 
 if [ "$@" = "" ]
 then
-    echo "ERROR: A network expression must be specified!" >&2
+    echo "ERROR: At least one network expression must be specified!" >&2
     exit 1
 else
-    networkFile=$(readlink -f $@)
+    while [ "$1" != "" ]
+    do
+	networkFiles="$networkFiles $(readlink -f $1)"
+	shift
+    done
 fi
 
 # Generate services model from network model
-servicesFile=`disnixos-genservices --no-out-link $showTraceArg $networkFile`
+servicesFile=`disnixos-genservices --no-out-link $showTraceArg $networkFiles`
 
 # Generate infrastructure model from network model
-infrastructureFile=`disnixos-geninfra --no-out-link $showTraceArg $networkFile`
+infrastructureFile=`disnixos-geninfra --no-out-link $showTraceArg $networkFiles`
 
 # Map NixOS configurations (services) to machines in the infrastructure model
 distributionFile=`disnix-gendist-roundrobin -s $servicesFile -i $infrastructureFile --no-out-link $showTraceArg`
