Replaced the ad-hoc textual infrastructure generator by one that uses the NixOS module

diff --git a/scripts/disnix-vm-env.in b/scripts/disnix-vm-env.in
--- a/scripts/disnix-vm-env.in
+++ b/scripts/disnix-vm-env.in
@@ -26,7 +26,6 @@ showUsage()
     echo "-s,--services       Services Nix expression which describes all components of the distributed system"
     echo "-n,--network        Network Nix expression which declares a NixOS configuration for each machine in the network"
     echo "-d,--distribution   Distribution Nix expression which maps services to machines in the network"
-    echo "--no-out-link       Do not create a 'result' symlink"
     echo "--show-trace        Shows a trace of the output"
     echo "-h,--help           Shows the usage of this command"
 }
@@ -61,9 +60,6 @@ do
 	-d|--distribution)
 	    distributionFile=`readlink -f $2`
 	    ;;
-	--no-out-link)
-	    noOutLink=1
-	    ;;
 	--show-trace)
 	    showTrace=1
 	    ;;
@@ -79,16 +75,21 @@ done
 # Validate the given options
 
 checkServicesFile
-checkInfrastructureFile
+
+if [ "$networkFile" = "" ]
+then
+    echo "ERROR: A network expression must be specified!" >&2
+    exit 1
+fi
+
 checkDistributionFile
-checkNoOutLink
 checkShowTrace
 
 # Generate virtual machines matching the configuration in the network Nix expression
-vmsPath=`nixos-build-vms --use-backdoor -n $networkFile $showTraceArg $noOutLinkArg`
+vmsPath=`nixos-build-vms --use-backdoor --no-out-link $showTraceArg $networkFile`
 
 # Generate infrastructure expression from network expression
-infrastructureFile=`disnix-generate-infra $showTraceArg $noOutLinkArg $networkFile`
+infrastructureFile=`disnix-generate-infra --use-backdoor --no-out-link $showTraceArg $networkFile`
 
 if [ ! -f ./vms ]
 then
